[versions]
commons-io = "2.21.0"
commons-lang3 = "3.20.0"
commons-text = "1.15.0"
dkim-gradle = "1.4.8"
dokkatoo = "2.4.0"
gson = "2.13.2"
junit = "5.14.2"
kaml = "0.104.0"
kotlin = "2.3.0"
kotlinx-coroutines = "1.10.2"
licenser = "0.6.1"
mockito-kotlin = "6.2.3"
nexus-publish-plugin = "2.0.0"
spotless = "7.2.1"
triumph-config = "1.0.5-SNAPSHOT"

[libraries]
commons-io = { group = "commons-io", name = "commons-io", version.ref = "commons-io" }
commons-lang3 = { group = "org.apache.commons", name = "commons-lang3", version.ref = "commons-lang3" }
commons-text = { group = "org.apache.commons", name = "commons-text", version.ref = "commons-text" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
kaml = { group = "com.charleskorn.kaml", name = "kaml", version.ref = "kaml" }
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-reactor = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-reactor", version.ref = "kotlinx-coroutines" }
mockito-kotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mockito-kotlin" }
triumph-config = { group = "me.mattstudios", name = "triumph-config", version.ref = "triumph-config" }

[plugins]
dkim-gradle = { id = "io.github.dkim19375.dkim-gradle", version.ref = "dkim-gradle" }
dokkatoo = { id = "dev.adamko.dokkatoo", version.ref = "dokkatoo" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
licenser = { id = "org.cadixdev.licenser", version.ref = "licenser" }
nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexus-publish-plugin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }


